// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>

class Window_Main {
  /**
   New file icon
  */
  Fl_File_Icon *icon; 
public:
  Window_Main();
  Fl_Double_Window *m_window;
  Fl_Group *group;
  Fl_File_Input *folder_input;
  Fl_Input *port_input;
  Fl_Button *start_btn;
private:
  inline void cb_start_btn_i(Fl_Button*, void*);
  static void cb_start_btn(Fl_Button*, void*);
public:
  Fl_Button *clear_btn;
private:
  inline void cb_clear_btn_i(Fl_Button*, void*);
  static void cb_clear_btn(Fl_Button*, void*);
public:
  Fl_Button *chooser;
private:
  inline void cb_chooser_i(Fl_Button*, void*);
  static void cb_chooser(Fl_Button*, void*);
public:
  Fl_Button *stop_btn;
private:
  inline void cb_stop_btn_i(Fl_Button*, void*);
  static void cb_stop_btn(Fl_Button*, void*);
public:
  Fl_Text_Display *output;
  void show();
  void folder_chooser();
  ~Window_Main();
};
#endif
